apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: backend-sa-role
 namespace: bar
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - watch
  - list


