apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-sa-rolebinding
  namespace: foo
roleRef:
  kind: Role
  name: frontend-sa-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: foo
